name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Haskell
        uses: haskell-actions/setup@fe9cd1cd1af94a23900c06738e73f6ddb092966a # v2.4
        with:
          ghc-version: "9.6.7"
          cabal-version: "3.14"

      - name: Run HLint
        uses: haskell-actions/hlint-setup@fe9cd1cd1af94a23900c06738e73f6ddb092966a # v2

      - name: Cache cabal
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}

      - name: Check with HLint
        uses: haskell-actions/hlint-run@eaca4cfbf4a69f4eb875df38b6bc3e1657020378 # v2
        with:
          path: src app test
          fail-on: warning

      - name: Build
        run: cabal build

      - name: Run tests
        run: cabal test all
